version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - db      
    networks:
      - custom_net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brands
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - custom_net      

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules      
    depends_on:
      - backend
    networks:
      - custom_net

  wordpress:
    image: wordpress:latest
    ports:
      - '8081:80'
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdb
    depends_on:
      - wpdb
    networks:
      - custom_net

  wpdb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - '3307:3306'
    volumes:
      - wpdb_data:/var/lib/mysql
    networks:
      - custom_net

volumes:
  db_data:
  wpdb_data:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
